### ISSUE TITLE
连接mssql报错

### ISSUE THREAD

**Issue by Tukali** [DeEpinGh0st/MDUT-Extend-Release#2]
连接mssql报错，设置的http代理，sqltools直接连没问题，mdut连接报错
![image](https://github.com/user-attachments/assets/2d6be0c7-7d76-455c-abd7-8c1dbfba9d4b)

![image](https://github.com/user-attachments/assets/4b135af5-97d7-479c-9210-cad66d051256)

报错信息如下：
java.lang.ArithmeticException: / by zero
	at Util.Base64XOR.xorWithKey(Base64XOR.java:113)
	at Util.Base64XOR.encode(Base64XOR.java:23)
	at Dao.MssqlHttpDao.executeSQLStatement(MssqlHttpDao.java:751)
	at Dao.MssqlHttpDao.getConnection(MssqlHttpDao.java:65)
	at Controller.MssqlController.lambda$null$2(MssqlController.java:215)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

**Comment by DeEpinGh0st** [comment]
好的,等我排查一下

**Comment by DeEpinGh0st** [comment]
Solved in [v1.3.0](https://github.com/DeEpinGh0st/MDUT-Extend-Release/releases/tag/v1.3.0)
